# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install latex linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-generic-recommended
    - name: Install latex mac
      if: ${{ matrix.os == 'macos-latest' }}
      run: brew cask install mactex
    - name: Install latex windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: choco install miktex
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pandas nbconvert aiohttp matplotlib beautifulsoup4 requests notebook jupyter pandoc
    - name: Test with pytest
      run: |
        pytest
